version: '3'

services:
  cloud_app:
    image: cloud
    build: ./
    container_name: cloud_container
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/postgres
      - localhost:5432/postgres

  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
        - "15432:5432"