tokenRepository:
  size: 1000

dataBase:
  schema: netology_diploma

jwt:
  secret: 56bc8451-8539-4607-b12f-96e315229c85
# secret сгенерирован через UUID randomUUID()
  lifetime: 10m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: validate
        default-schema: ${dataBase.schema}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${dataBase.schema}
  sql:
    init:
      mode: always